### ISSUE TITLE
ImportError: cannot import name 'find_loader' from 'importlib'

### ISSUE THREAD

**Issue by rohit-panda-styldod** [modelscope/scepter#68]
Have installed dependencies from `https://github.com/ali-vilab/ACE/blob/main/requirements.txt`, getting this error 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/miniconda3/envs/ACEconda.1024.v2/lib/python3.12/site-packages/scepter/__init__.py", line 6, in <module>
    from scepter.modules import data, model, opt, solver, transform, utils
  File "/home/ubuntu/miniconda3/envs/ACEconda.1024.v2/lib/python3.12/site-packages/scepter/modules/__init__.py", line 3, in <module>
    from scepter.modules import (data, inference, model, opt, solver, transform,
  File "/home/ubuntu/miniconda3/envs/ACEconda.1024.v2/lib/python3.12/site-packages/scepter/modules/inference/__init__.py", line 3, in <module>
    from scepter.modules.inference.diffusion_inference import DiffusionInference
  File "/home/ubuntu/miniconda3/envs/ACEconda.1024.v2/lib/python3.12/site-packages/scepter/modules/inference/diffusion_inference.py", line 11, in <module>
    from scepter.modules.model.network.diffusion.diffusion import GaussianDiffusion
  File "/home/ubuntu/miniconda3/envs/ACEconda.1024.v2/lib/python3.12/site-packages/scepter/modules/model/__init__.py", line 4, in <module>
    from scepter.modules.model import (backbone, embedder, head, loss, metric,
  File "/home/ubuntu/miniconda3/envs/ACEconda.1024.v2/lib/python3.12/site-packages/scepter/modules/model/backbone/__init__.py", line 3, in <module>
    from scepter.modules.model.backbone import (ace, autoencoder, flux, image, cogvideox,
  File "/home/ubuntu/miniconda3/envs/ACEconda.1024.v2/lib/python3.12/site-packages/scepter/modules/model/backbone/unet/__init__.py", line 3, in <module>
    from scepter.modules.model.backbone.unet.unet_module import (DiffusionUNet,
  File "/home/ubuntu/miniconda3/envs/ACEconda.1024.v2/lib/python3.12/site-packages/scepter/modules/model/backbone/unet/unet_module.py", line 9, in <module>
    from scepter.modules.model.backbone.unet.unet_utils import (
  File "/home/ubuntu/miniconda3/envs/ACEconda.1024.v2/lib/python3.12/site-packages/scepter/modules/model/backbone/unet/unet_utils.py", line 7, in <module>
    from importlib import find_loader
ImportError: cannot import name 'find_loader' from 'importlib'
``` 

The below line itself is causing the error on my end
`from scepter.modules.utils.config import Config`

This error doesn't appear while working with Scepter 1.2.0, i.e. which was there in the dependencies before the last commit occurred in the ACE repo

<img width="1512" alt="Screenshot 2024-12-04 at 1 35 40 PM" src="https://github.com/user-attachments/assets/26a747d5-eb9d-4193-91a7-5f0cdc2624a6">

**Comment by yaosheng216** [comment]
This error may be related to your python version, please make sure the python version is consistent with mine, or try another version.
<img width="808" alt="截屏2024-12-05 17 23 34" src="https://github.com/user-attachments/assets/f0c63edd-5a51-469b-b440-4093322061ca">

**Comment by rohit-panda-styldod** [comment]
Sure, thanks!
